apiVersion: batch/v1
kind: Job
metadata:
  name: migrate4
spec:
  template:
    spec:
      containers:
        - name: displaydoctors
          image: athishwaran/display:0.0.3
          command: ['python', 'manage.py', 'migrate']
          env:
          - name: DJANGO_SETTINGS_MODULE
            value: "healthcareservices.settings"
      restartPolicy: Never
  backoffLimit: 1
