apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:latest
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: your_username
        - name: RABBITMQ_DEFAULT_PASS
          value: your_password
        resources:
            limits:
              memory: "512Mi" # Maximum memory limit for the container
              cpu: "500m"     # Maximum CPU limit for the container (0.5 cores)
            requests:
              memory: "256Mi" # Initial memory request for the container
              cpu: "250m"     # Initial CPU request for the container (0.25 cores)
